---
slug: :followingcontrol
depends:
  mikutter: '3.3'
  plugin:
  - gtk
  - gui
  - user_detail_view
  - skin
  - twitter
version: '1.1'
author: toshi_a
name: フォロー
description: フォロイー、フォロワーを表示するタブを追加する
