---
:slug: :followingcontrol
:depends:
  :mikutter: '5.0'
  :plugin:
  - gtk3
  - gui
  - user_detail_view
  - skin
  - twitter
:version: '2.0'
:author: toshi_a
:name: フォロー
:description: フォロイー、フォロワーを表示するタブを追加する
